name: Actions
on: workflow_dispatch

jobs:
  ubuntu-ssh:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup
      run: |
         sudo apt-get -qq -y update
         sudo apt-get install zsh
         sudo chsh -s /usr/bin/zsh runner

    - name: SSH connection to Actions
      continue-on-error: true    
      timeout-minutes: 340    
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets._NGROK_TOKEN }}
        NGROK_REGION: us
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT }}

    - name: Trigger another workflow
      run: |
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"master"}'
